# Generated by Django 5.2.1 on 2025-05-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(help_text='Hostname or IP address of the database server', max_length=255)),
                ('database_name', models.CharField(help_text='Name of the database', max_length=255)),
                ('user', models.CharField(help_text='Database username', max_length=255)),
                ('password', models.CharField(help_text='Database password', max_length=255)),
                ('driver', models.CharField(choices=[('postgres', 'PostgreSQL')], help_text='Database driver', max_length=50)),
                ('port', models.PositiveIntegerField(default=5432, help_text='Port number of the database server')),
            ],
        ),
    ]
