# Generated by Django 5.2.1 on 2025-05-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='table_names',
            field=models.TextField(blank=True, help_text='JSON list of table names in the database', null=True),
        ),
    ]
