# Generated by Django 5.2.1 on 2025-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_task_task_id_task_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
