# Generated by Django 5.2.1 on 2025-05-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_task_completed_at_remove_task_result_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
