# Generated by Django 5.2.1 on 2025-05-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='table_name',
            field=models.CharField(default='mast', max_length=255),
            preserve_default=False,
        ),
    ]
