# Generated by Django 5.2.1 on 2025-05-18 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_task_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='database_name',
            field=models.CharField(default="gridmaps_db", help_text='Name of the database', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
