# Generated by Django 5.2.1 on 2025-05-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_task_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MVTLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('mbtiles_path', models.CharField(max_length=255)),
            ],
        ),
    ]
