# Generated by Django 5.2.1 on 2025-05-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_mvtlayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvtlayer',
            name='db_connection',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app.databaseconnection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mvtlayer',
            name='geometry_type',
            field=models.CharField(default='POINT', max_length=255),
            preserve_default=False,
        ),
    ]
