# Generated by Django 5.2.1 on 2025-05-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_mvtlayer_db_connection_mvtlayer_geometry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mvtlayer',
            name='scheme',
            field=models.CharField(default='tms', max_length=25),
        ),
    ]
